"""create tables

Revision ID: 2cc6b2c049bb
Revises: b1df1fe36fdd
Create Date: 2023-03-29 11:33:20.321790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cc6b2c049bb'
down_revision = 'b1df1fe36fdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('pkid', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    # op.create_table('user',
    # sa.Column('pkid', sa.Integer(), nullable=False),
    # sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    # sa.Column('email', sa.String(length=255), nullable=True),
    # sa.Column('password', sa.String(), nullable=True),
    # sa.Column('wallet_balance', sa.Integer(), nullable=True),
    # sa.Column('first_name', sa.String(length=255), nullable=True),
    # sa.Column('last_name', sa.String(length=255), nullable=True),
    # sa.Column('phone_number', sa.BigInteger(), nullable=True),
    # sa.Column('date_of_birth', sa.Date(), nullable=True),
    # sa.Column('date_registered', sa.DateTime(), nullable=True),
    # sa.Column('email_verified', sa.Boolean(), nullable=True),
    # sa.Column('google_id', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('pkid'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('plans')
    # ### end Alembic commands ###
