"""realtionship

Revision ID: 3961f2467c39
Revises: 57363e65c267
Create Date: 2023-04-02 00:31:13.367064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3961f2467c39'
down_revision = '57363e65c267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('cart', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('cart', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'cart', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'is_paid')
    op.drop_column('cart', 'amount')
    op.drop_column('cart', 'user')
    # ### end Alembic commands ###
