"""312

Revision ID: 39794b6b9f7e
Revises: 7e3d16ca281f
Create Date: 2023-03-18 15:31:01.492477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39794b6b9f7e'
down_revision = '7e3d16ca281f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
