"""added datetime and fix a bug

Revision ID: 4cb8542bf7f3
Revises: 2cc6b2c049bb
Create Date: 2023-03-29 15:11:26.442897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb8542bf7f3'
down_revision = '2cc6b2c049bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
