"""adds created_at and paid_at datetime columns

Revision ID: 538a450db8a4
Revises: 8b93be8e0012
Create Date: 2023-03-30 01:51:56.048898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538a450db8a4'
down_revision = '8b93be8e0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'paid_at')
    op.drop_column('transaction', 'created_at')
    # ### end Alembic commands ###
