"""products_and_cart

Revision ID: 57363e65c267
Revises: b050bea33215
Create Date: 2023-04-01 23:57:39.910967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57363e65c267'
down_revision = 'b050bea33215'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('pkid', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    op.create_table('products',
    sa.Column('pkid', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('cart')
    # ### end Alembic commands ###
