"""remove datetime columns

Revision ID: 8b93be8e0012
Revises: a36e9565e70c
Create Date: 2023-03-30 01:47:17.895136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b93be8e0012'
down_revision = 'a36e9565e70c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'created_at')
    op.drop_column('transaction', 'paid_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('paid_at', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('created_at', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
