"""312

Revision ID: 8d3df82eb54b
Revises: f28b627c64ae
Create Date: 2023-03-17 00:56:30.894782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3df82eb54b'
down_revision = 'f28b627c64ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'dob')
    # ### end Alembic commands ###
