"""312

Revision ID: 9284b3478ec6
Revises: 8d3df82eb54b
Create Date: 2023-03-17 00:59:23.626933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9284b3478ec6'
down_revision = '8d3df82eb54b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
