"""user foreign key added

Revision ID: a36e9565e70c
Revises: 3d8f4116fd14
Create Date: 2023-03-29 18:41:49.396813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a36e9565e70c'
down_revision = '3d8f4116fd14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'transaction', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user')
    # ### end Alembic commands ###
