"""plan name added with new length

Revision ID: c19020ad64e1
Revises: feb67b36edf4
Create Date: 2023-04-04 12:31:19.007032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19020ad64e1'
down_revision = 'feb67b36edf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'name')
    # ### end Alembic commands ###
