"""Added wallet_balance field to User model

Revision ID: e635b077322e
Revises: 4003da70056f
Create Date: 2023-03-22 22:04:23.477029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e635b077322e'
down_revision = '4003da70056f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wallet_balance')
    # ### end Alembic commands ###
