"""plan name column removal to correct character length

Revision ID: feb67b36edf4
Revises: bee210102c9f
Create Date: 2023-04-04 12:25:19.152958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb67b36edf4'
down_revision = 'bee210102c9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('name', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
